services:
  spring-boot-server:
    image: ${DOCKER_USERNAME}/hotel-reservation-backend:latest
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      SERVER_SSL_ENABLED: "false"
      SPRING_DATA_REDIS_REPOSITORIES_ENABLED: "false"
      SPRING_AUTOCONFIGURE_EXCLUDE: org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

    env_file:
      - .env
    depends_on:
      redis-server:
        condition: service_healthy

  redis-server:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10