spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/hotel_project_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 50
  data:
    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid email profile
            redirect-uri: "https://localhost:8443/api/customers/google/callback"
            #callback-uri: "https://localhost:5173/oauth/google?code="
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri:  https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: myserver
  servlet:
    session:
      cookie:
        same-site: none
        secure: true

oauth:
  google:
    client-id: xxxx
    client-secret: yyyy
    redirect-uri: https://localhost:8443/oauth/google/redirect
  kakao:
    client-id: xxxx
    redirect-uri: https://localhost:8443/oauth/kakao/redirect

jwt:
  secret: ${JWT_SECRET}
  access-expiration-minutes: 15
  refresh-expiration-days: 14

iamport:
  api-key: ${IAMPORT_API_KEY}
  secret: ${IAMPORT_SECRET}

file:
  dir: "C:/Users/...사진 저장할 주소"

app:
  base-url: https://localhost:8080

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    #staysplit.hotel_reservation: DEBUG
    p6spy: INFO
    com.p6spy: INFO

