spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/staysplit
    username: root
    password: qwer1234
  jpa:
    show-sql: true
    database: mysql
    hibernate.ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid email profile
            redirect-uri: "https://localhost:8443/api/customers/google/callback"
            callback-uri: "https://localhost:5173/oauth/google?code="
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri:  https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

oauth:
  google:
    client-id: xxxx
    client-secret: yyyy
    redirect-uri: https://localhost:8443/oauth/google/redirect
  kakao:
    client-id: xxxx
    redirect-uri: https://localhost:8443/oauth/kakao/redirect

jwt:
  secret: dG9ieXNwcmluZ2Jvb3RjYW1wZ3VpZGVkYXRhYmFzZWVuZ2xpc2hqYXBhbnNlZG9zaWJvb2tzdG9ieXNwcmluZ2Jvb3RjYW1w
  expiration: 1800


iamport:
  api-key: 0165681344553345
  secret: XL8h5EJaZDMiEQyzqIIlsV8BkIQOTD23ZaLU2abAWPlNzy2ijXIgk6lbv6XkZhI4hQWfmSFYuUifTRWw

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: myserver
  servlet:
    session:
      cookie:
        same-site: none
        secure: true

file:
  dir: "C:/Users/...사진 저장할 주소"

file:
  dir: "C:/Users/...사진 저장할 주소"

app:
  base-url: https://localhost:8080

  logging:
    level:
      org.springframework.security: DEBUG