spring:
  profiles:
    active : local

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 50

  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false

  cloud:
    aws:
      s3:
        bucket: ${AWS_S3_BUCKET}
      region:
        static: ${AWS_REGION}
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: http://localhost:5173/api/auth/google/callback
    scope: openid email profile

jwt:
  secret: ${JWT_SECRET}
  access-expiration-minutes: 15
  refresh-expiration-days: 14

portone:
  api:
    secret: ${PORTONE_API_SECRET}

app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173}

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    p6spy: INFO
    com.p6spy: INFO

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: splitstay #Grafana에서 구분할 앱 이름